### ISSUE TITLE
How to set up Seneca with Docker Swarm

### ISSUE THREAD

**Issue by vforv** [senecajs/seneca#672]
Hello I am trying to set up simple Seneca project in docker swarm on Digitalocean.

Repo:
https://github.com/vforv/hapi-seneca-ts

And here is my set up:
https://github.com/vforv/hapi-seneca-ts/blob/master/system/fuge/docker-swarm.yml

```
version: '3'

networks:
  trifacta:
    driver: overlay

services:
  bases:
    image: vforv/hapi-seneca-ts:v1
    networks:
      trifacta:
        aliases: 
          - bases
    command: bash -c "cd bases-service && npm start"
  api:
    image: vforv/api-gateway:v1
    ports:
        - "5000:5000"
    networks:
        - trifacta
    command: bash -c "cd api-gateway && npm start"
  ping:
    image: vforv/ping-service:v1
    networks:
        - trifacta
    command: bash -c "cd ping-service && npm start"
```

It not working currently it looks like some problem with service connections... I get somethings like this:
DEATH LOOP....

What can be a problem?
